### ISSUE TITLE
Upload GeoTiff Error You can't execute queries until the end of the 'atomic' block

### ISSUE THREAD

**Issue by jeff-bradley** [GeoNode/geonode-importer#197] opened 2023-09-01 15:02 UTC
## Expected Behavior
Upload Geotiff file successfully

## Actual Behavior
Error of "An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.. Request: None"

## Steps to Reproduce the Problem

  1. Download and unzip wildlife areas https://sitewindright.s3.amazonaws.com/KeyWildlifeAreas_Solar_GT_20210907.zip
  2. Upload Geotiff to geonode
  3. Upload Fails

## Specifications

  - GeoNode version: 4.1
  - Installation type (vanilla, geonode-project): Vanilla
  - Installation method (manual, docker): docker
  - Platform: Windows WSL Ubuntu 22
  - Additional details: ExecutionRequest 
  ```json
 {
            "exec_id": "5e0c56a8-98c7-40ab-b9f6-915426202776",
            "status": "failed",
            "func_name": "rollback",
            "created": "2023-09-01T14:54:11.136364Z",
            "finished": "2023-09-01T14:54:15.553520Z",
            "last_updated": "2023-09-01T14:54:15.553538Z",
            "input_params": {
                "files": {
                    "tif_file": "/mnt/volumes/statics/uploaded/tmp8s7iro8f/KeyWildlifeAreas_Solar_GT_20210907.tif",
                    "base_file": "/mnt/volumes/statics/uploaded/tmp8s7iro8f/KeyWildlifeAreas_Solar_GT_20210907.tif"
                },
                "total_layers": 1,
                "store_spatial_file": true,
                "handler_module_path": "importer.handlers.geotiff.handler.GeoTiffFileHandler",
                "skip_existing_layers": false,
                "overwrite_existing_layer": false
            },
            "output_params": {
                "errors": [
                    "Task: importer.create_geonode_resource raised an error during actions for layer: import: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.. Request: None"
                ],
                "failed_layers": [
                    "import"
                ]
            },
            "step": "importer.rollback",
            "log": "An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.. Request: None",
            "name": "KeyWildlifeAreas_Solar_GT_20210907.tif",
            "action": "import",
            "source": "upload",
            "user": 1000,
            "geonode_resource": null,
            "link": "http://localhost/api/v2/executionrequest/5e0c56a8-98c7-40ab-b9f6-915426202776"
        },

```

**Comment by giohappy** [comment] 2023-09-04 09:25
I've reopened and tranfered the issue inside the importer repo.

@mattiagiupponi in case of unsupported CRS a more informative error should be returned by the importer.
"_An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block. Request: None_" is very cryptic, to say the least :)

**Comment by ridoo** [comment] 2023-09-04 12:08
May I ask if adding additional CRSs in Geoserver would also solve this problem?

**Comment by giohappy** [comment] 2023-09-05 10:50
@jeff-bradley after some troubleshooting we found that the problem is with the CRS assigned to the Geotiff. It's not EPSG:5070 but ESRI:102039. Geoserver doesn't parese this CRS correctly (to be investigated why) but it creates the layer: Everything is fine if we reproject the original tiff to EPSG:5070.

We are going to open an issue for the importer to trigger a rollback if Geoserver fails at returning a valid CRS before pubslighing the dataset in GeoNode.

**Comment by mattiagiupponi** [comment] 2023-09-11 14:37
I just merge a PR which will raise a clear error if the Srid is not recognied correctly. 
At least should be more clear the issue instead of the "atomic block" exception

**Comment by mattiagiupponi** [comment] 2023-09-26 09:27
This was resolved via https://github.com/GeoNode/geonode-importer/issues/198

**Closed by mattiagiupponi** 2023-09-26 09:27 UTC
